CREATE TABLE Employee (
    EMP_ID CHAR(5) PRIMARY KEY,
    NAME VARCHAR(50) NOT NULL,
    EMAIL VARCHAR(100),
    FLOOR_SEAT_SEQ INT,
    CONSTRAINT FK_SEAT
        FOREIGN KEY (FLOOR_SEAT_SEQ)
        REFERENCES SeatingChart(FLOOR_SEAT_SEQ)
);

CREATE TABLE SeatingChart (
    FLOOR_SEAT_SEQ INT PRIMARY KEY,
    FLOOR_NO INT NOT NULL,
    SEAT_NO INT NOT NULL
);
